image: archlinux
secrets:
- 36f65f02-9e26-497e-94d7-f1cd8ba3ef7a
packages:
  - go
sources:
  - https://github.com/go-ap/activitypub
environment:
  GO111MODULE: 'on'
tasks:
  - setup: |
      cd activitypub && go mod download
  - tests: |
      cd activitypub && make test
  - coverage: |
      set -a +x
      cd activitypub && make coverage
      GIT_SHA=$(git rev-parse --verify HEAD)
      GIT_BRANCH=$(git name-rev --name-only HEAD)
      source ~/.code-cov.sh
      curl -X POST \
          --data-binary @activitypub.coverprofile \
           -H 'Accept: application/json' \
          "https://codecov.io/upload/v2?commit=${GIT_SHA}&token=${PUB_TOKEN}&branch=${GIT_BRANCH}&service=custom"
