image: archlinux
packages:
  - go
  - golangci-lint
sources:
  - https://github.com/go-ap/activitypub
secrets:
  - b8faddab-aa0a-442c-96af-ead35b021146
environment:
  GO111MODULE: 'on'
tasks:
  - fmt: |
      cd activitypub
      test -z $(gofmt -l .)
  - tests: |
      cd activitypub
      make test
  - coverage: |
      cd activitypub
      git switch -C master origin/master
      make coverage
      go tool goveralls -flagname unit-tests -service=${CI_NAME} -coverprofile activitypub.coverprofile -repotokenfile ~/.coveralls.tok
  - lint: |
      cd activitypub
      golangci-lint run || true
